export const generateCSVTemplate = () => {
  const headers = [
    'Product Code',
    'Amazon ASIN',
    'Name',
    'Sku Id',
    'Description',
    'Selling Price',
    'MRP',
    'Cost Price',
    'Quantity',
    'Packaging Length (in cm)',
    'Packaging Breadth (in cm)',
    'Packaging Height (in cm)',
    'Packaging Weight (in kg)',
    'GST %',
    'Image 1',
    'Image 2',
    'Image 3',
    'Image 4',
    'Image 5',
    'Image 6',
    'Image 7',
    'Image 8',
    'Image 9',
    'Image 10',
    'Video 1',
    'Video 2',
    'Product Type',
    'Size',
    'Colour',
    'Return/Exchange Condition',
    'HSN Code',
    'Customisation Id',
    'Category ID',
    'Sub Category ID',
    'Store ID'
  ];

  const sampleData = [
    'PROD001',
    'B08N5WRWNW',
    'Sample Smartphone',
    'SKU-SAMPLE-001',
    'Latest smartphone with advanced features',
    '29999.00',
    '34999.00',
    '25000.00',
    '50',
    '15.5',
    '7.5',
    '0.8',
    '0.18',
    '18.00',
    'http://localhost:5000/uploads/products/sample-1.jpg',
    'http://localhost:5000/uploads/products/sample-2.jpg',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'Electronics',
    '6.1 inch',
    'Black',
    '7 days return, 1 year warranty',
    '8517',
    'SAMPLE-CUST',
    '1',
    '37',
    'ce32fe90-7eaa-11f0-a328-f5704f3e47ab'
  ];

  const csvContent = [headers.join(','), sampleData.join(',')].join('\n');
  
  const blob = new Blob([csvContent], { type: 'text/csv' });
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'product-bulk-upload-template.csv';
  a.click();
  window.URL.revokeObjectURL(url);
};

export const csvHeaders = [
  'Product Code',
  'Amazon ASIN',
  'Name',
  'Sku Id',
  'Description',
  'Selling Price',
  'MRP',
  'Cost Price',
  'Quantity',
  'Packaging Length (in cm)',
  'Packaging Breadth (in cm)',
  'Packaging Height (in cm)',
  'Packaging Weight (in kg)',
  'GST %',
  'Image 1',
  'Image 2',
  'Image 3',
  'Image 4',
  'Image 5',
  'Image 6',
  'Image 7',
  'Image 8',
  'Image 9',
  'Image 10',
  'Video 1',
  'Video 2',
  'Product Type',
  'Size',
  'Colour',
  'Return/Exchange Condition',
  'HSN Code',
  'Customisation Id',
  'Category ID',
  'Sub Category ID',
  'Store ID'
];
